FROM youken9980/temurin:8-jdk-alpine AS maven

RUN apk --update --no-cache add zip
# https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
ARG APACHE_MIRROR="https://dlcdn.apache.org"

ENV MAVEN_VERSION="3.9.8"
ENV MAVEN_DOWNLOAD_URL="${APACHE_MIRROR}/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz"
ENV MAVEN_HOME="/usr/local/maven"
ENV MAVEN_REPO="/usr/local/repository/maven"

RUN axel -n 8 -o maven.tar.gz ${MAVEN_DOWNLOAD_URL} && \
    mkdir -p ${MAVEN_HOME} && \
    tar -zxvf maven.tar.gz -C ${MAVEN_HOME} --strip-components=1 --no-same-owner && \
    cp ${MAVEN_HOME}/conf/settings.xml ${MAVEN_HOME}/conf/settings.xml.bak

RUN sed -i '/  <!-- localRepository/i\  <localRepository>${MAVEN_REPO}</localRepository>' ${MAVEN_HOME}/conf/settings.xml && \
    sed -i '/    <!-- mirror/i\    <mirror>' ${MAVEN_HOME}/conf/settings.xml && \
    sed -i '/    <!-- mirror/i\        <id>aliyunmaven</id>' ${MAVEN_HOME}/conf/settings.xml && \
    sed -i '/    <!-- mirror/i\        <mirrorOf>central</mirrorOf>' ${MAVEN_HOME}/conf/settings.xml && \
    sed -i '/    <!-- mirror/i\        <name>阿里云公共仓库</name>' ${MAVEN_HOME}/conf/settings.xml && \
    sed -i '/    <!-- mirror/i\        <url>https://maven.aliyun.com/repository/public</url>' ${MAVEN_HOME}/conf/settings.xml && \
    sed -i '/    <!-- mirror/i\    </mirror>' ${MAVEN_HOME}/conf/settings.xml


FROM youken9980/temurin:8-jdk-alpine AS gradle

ARG GITHUB_MIRROR="https://github.com"

RUN apk --update --no-cache add zip

# https://services.gradle.org/distributions/gradle-8.8-bin.zip
# https://github.com/gradle/gradle-distributions/releases/download/v8.8.0/gradle-8.8-bin.zip

ENV GRADLE_VERSION="8.8"
# ENV GRADLE_DOWNLOAD_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
ENV GRADLE_DOWNLOAD_URL="${GITHUB_MIRROR}/gradle/gradle-distributions/releases/download/v${GRADLE_VERSION}.0/gradle-${GRADLE_VERSION}-bin.zip"
ENV GRADLE_HOME="/usr/local/gradle"

RUN axel -n 8 -o gradle.zip ${GRADLE_DOWNLOAD_URL} && \
    unzip gradle.zip && \
    mv /gradle-${GRADLE_VERSION} ${GRADLE_HOME}


FROM youken9980/temurin:8-jdk-alpine
LABEL maintainer="YangJian <youken9980@163.com>"

ENV MAVEN_HOME="/usr/local/maven"
ENV MAVEN_REPO="/usr/local/repository/maven"
ENV MAVEN_REPOSITORY="${MAVEN_REPO}"
ENV M2_REPO="${MAVEN_REPO}"

ENV GRADLE_HOME="/usr/local/gradle"
ENV GRADLE_REPO="/usr/local/repository/gradle"
ENV GRADLE_USER_HOME="${GRADLE_REPO}"

ENV PATH="${PATH}:${MAVEN_HOME}/bin:${GRADLE_HOME}/bin"

RUN apk --update --no-cache add git subversion perl-xml-xpath yq && \
    mkdir -p ${MAVEN_REPO} ${GRADLE_REPO} && \
    \
    rm -rf /var/cache/apk/*.*

COPY --chown=root:root --from=maven ${MAVEN_HOME} ${MAVEN_HOME}
COPY --chown=root:root --from=gradle ${GRADLE_HOME} ${GRADLE_HOME}

VOLUME ["/app","/usr/local/repository/maven","/usr/local/repository/gradle"]

STOPSIGNAL SIGTERM

CMD [ "/bin/sh" ]
